using PRIO.src.Modules.ControlAccess.Users.Dtos;

namespace PRIO.src.Modules.Measuring.WellEvents.Dtos
{
    public class WellEventByIdDto
    {
        public Guid Id { get; set; }
        public string Uep { get; set; }
        public string AutoGeneratedId { get; set; }
        public string Installation { get; set; }
        public string Field { get; set; }
        public string EventDateAndHour { get; set; }
        public string? EventRelated { get; set; }
        public string? SystemRelated { get; set; }
        public string? Reason { get; set; }
        public string? StatusAnp { get; set; }
        public string? StateAnp { get; set; }
        public UserDTO CreatedBy { get; set; }
        public UserDTO? UpdatedBy { get; set; }

        public List<ReasonDetailedDto> DetailedClosing { get; set; }
    }

    public class ReasonDetailedDto
    {
        public Guid Id { get; set; }
        public string SystemRelated { get; set; }
        public string StartDate { get; set; }
        public string? EndDate { get; set; }
        public string? Downtime { get; set; }
        public UserDTO? UpdatedBy { get; set; }
        public UserDTO CreatedBy { get; set; }
        public bool IsJobGenerated { get; set; }

    }

    public class UpdateReasonDetailedDto
    {
        public ReasonDetailedDto? BeforeReason { get; set; }
        public ReasonDetailedDto UpdatedReason { get; set; }
        public ReasonDetailedDto? NextReason { get; set; }
    }
}
