namespace PRIO.DTOS
{
    public class _001DTO
    {
        public Guid Id { get; set; }
        public string? NUM_SERIE_ELEMENTO_PRIMARIO_001 { get; set; }
        public int? COD_INSTALACAO_001 { get; set; }
        public string? COD_TAG_PONTO_MEDICAO_001 { get; set; }
        public string? NUM_SERIE_COMPUTADOR_VAZAO_001 { get; set; }
        public DateTime? DHA_COLETA_001 { get; set; }
        public decimal? MED_TEMPERATURA_001 { get; set; }
        public decimal? MED_PRESSAO_ATMSA_001 { get; set; }
        public decimal? MED_PRESSAO_RFRNA_001 { get; set; }
        public decimal? MED_DENSIDADE_RELATIVA_001 { get; set; }
        public string? DSC_VERSAO_SOFTWARE_001 { get; set; }
        public decimal? ICE_METER_FACTOR_1_001 { get; set; }
        public decimal? ICE_METER_FACTOR_2_001 { get; set; }
        public decimal? ICE_METER_FACTOR_3_001 { get; set; }
        public decimal? ICE_METER_FACTOR_4_001 { get; set; }
        public decimal? ICE_METER_FACTOR_5_001 { get; set; }
        public decimal? ICE_METER_FACTOR_6_001 { get; set; }
        public decimal? ICE_METER_FACTOR_7_001 { get; set; }
        public decimal? ICE_METER_FACTOR_8_001 { get; set; }
        public decimal? ICE_METER_FACTOR_9_001 { get; set; }
        public decimal? ICE_METER_FACTOR_10_001 { get; set; }
        public decimal? ICE_METER_FACTOR_11_001 { get; set; }
        public decimal? ICE_METER_FACTOR_12_001 { get; set; }
        public decimal? ICE_METER_FACTOR_13_001 { get; set; }
        public decimal? ICE_METER_FACTOR_14_001 { get; set; }
        public decimal? ICE_METER_FACTOR_15_001 { get; set; }
        public decimal? QTD_PULSOS_METER_FACTOR_1_001 { get; set; }
        public decimal? QTD_PULSOS_METER_FACTOR_2_001 { get; set; }
        public decimal? QTD_PULSOS_METER_FACTOR_3_001 { get; set; }
        public decimal? QTD_PULSOS_METER_FACTOR_4_001 { get; set; }
        public decimal? QTD_PULSOS_METER_FACTOR_5_001 { get; set; }
        public decimal? QTD_PULSOS_METER_FACTOR_6_001 { get; set; }
        public decimal? QTD_PULSOS_METER_FACTOR_7_001 { get; set; }
        public decimal? QTD_PULSOS_METER_FACTOR_8_001 { get; set; }
        public decimal? QTD_PULSOS_METER_FACTOR_9_001 { get; set; }
        public decimal? QTD_PULSOS_METER_FACTOR_10_001 { get; set; }
        public decimal? QTD_PULSOS_METER_FACTOR_11_001 { get; set; }
        public decimal? QTD_PULSOS_METER_FACTOR_12_001 { get; set; }
        public decimal? QTD_PULSOS_METER_FACTOR_13_001 { get; set; }
        public decimal? QTD_PULSOS_METER_FACTOR_14_001 { get; set; }
        public decimal? QTD_PULSOS_METER_FACTOR_15_001 { get; set; }
        public decimal? ICE_K_FACTOR_1_001 { get; set; }
        public decimal? ICE_K_FACTOR_2_001 { get; set; }
        public decimal? ICE_K_FACTOR_3_001 { get; set; }
        public decimal? ICE_K_FACTOR_4_001 { get; set; }
        public decimal? ICE_K_FACTOR_5_001 { get; set; }
        public decimal? ICE_K_FACTOR_6_001 { get; set; }
        public decimal? ICE_K_FACTOR_7_001 { get; set; }
        public decimal? ICE_K_FACTOR_8_001 { get; set; }
        public decimal? ICE_K_FACTOR_9_001 { get; set; }
        public decimal? ICE_K_FACTOR_10_001 { get; set; }
        public decimal? ICE_K_FACTOR_11_001 { get; set; }
        public decimal? ICE_K_FACTOR_12_001 { get; set; }
        public decimal? ICE_K_FACTOR_13_001 { get; set; }
        public decimal? ICE_K_FACTOR_14_001 { get; set; }
        public decimal? ICE_K_FACTOR_15_001 { get; set; }
        public decimal? QTD_PULSOS_K_FACTOR_1_001 { get; set; }
        public decimal? QTD_PULSOS_K_FACTOR_2_001 { get; set; }
        public decimal? QTD_PULSOS_K_FACTOR_3_001 { get; set; }
        public decimal? QTD_PULSOS_K_FACTOR_4_001 { get; set; }
        public decimal? QTD_PULSOS_K_FACTOR_5_001 { get; set; }
        public decimal? QTD_PULSOS_K_FACTOR_6_001 { get; set; }
        public decimal? QTD_PULSOS_K_FACTOR_7_001 { get; set; }
        public decimal? QTD_PULSOS_K_FACTOR_8_001 { get; set; }
        public decimal? QTD_PULSOS_K_FACTOR_9_001 { get; set; }
        public decimal? QTD_PULSOS_K_FACTOR_10_001 { get; set; }
        public decimal? QTD_PULSOS_K_FACTOR_11_001 { get; set; }
        public decimal? QTD_PULSOS_K_FACTOR_12_001 { get; set; }
        public decimal? QTD_PULSOS_K_FACTOR_13_001 { get; set; }
        public decimal? QTD_PULSOS_K_FACTOR_14_001 { get; set; }
        public decimal? QTD_PULSOS_K_FACTOR_15_001 { get; set; }
        public decimal? ICE_CUTOFF_001 { get; set; }
        public decimal? ICE_LIMITE_SPRR_ALARME_001 { get; set; }
        public decimal? ICE_LIMITE_INFRR_ALARME_001 { get; set; }
        public string? IND_HABILITACAO_ALARME_1_001 { get; set; }
        public string? NUM_SERIE_1_001 { get; set; }
        public decimal? MED_PRSO_LIMITE_SPRR_ALRME_001 { get; set; }
        public decimal? MED_PRSO_LMTE_INFRR_ALRME_001 { get; set; }
        public string? IND_HABILITACAO_ALARME_2_001 { get; set; }
        public decimal? MED_PRSO_ADOTADA_FALHA_001 { get; set; }
        public string? DSC_ESTADO_INSNO_CASO_FALHA_001 { get; set; }
        public string? IND_TIPO_PRESSAO_CONSIDERADA_001 { get; set; }
        public string? NUM_SERIE_2_001 { get; set; }
        public decimal? MED_TMPTA_SPRR_ALARME_001 { get; set; }
        public decimal? MED_TMPTA_INFRR_ALRME_001 { get; set; }
        public string? IND_HABILITACAO_ALARME_3_001 { get; set; }
        public decimal? MED_TMPTA_ADTTA_FALHA_001 { get; set; }
        public string? DSC_ESTADO_INSTRUMENTO_FALHA_1_001 { get; set; }
        public string? NUM_SERIE_3_001 { get; set; }
        public decimal? PCT_LIMITE_SUPERIOR_1_001 { get; set; }
        public decimal? PCT_LIMITE_INFERIOR_1_001 { get; set; }
        public string? IND_HABILITACAO_ALARME_4_001 { get; set; }
        public decimal? PCT_ADOTADO_CASO_FALHA_1_001 { get; set; }
        public string? NUM_SERIE_4_001 { get; set; }
        public decimal? PCT_LIMITE_SUPERIOR_2_001 { get; set; }
        public decimal? PCT_LIMITE_INFERIOR_2_001 { get; set; }
        public string? IND_HABILITACAO_ALARME_5_001 { get; set; }
        public decimal? PCT_ADOTADO_CASO_FALHA_2_001 { get; set; }
        public decimal? DSC_ESTADO_INSTRUMENTO_FALHA_3_001 { get; set; }
        public string? DSC_ESTADO_INSTRUMENTO_FALHA_2_001 { get; set; }
        public DateTime? DHA_INICIO_PERIODO_MEDICAO_001 { get; set; }
        public DateTime? DHA_FIM_PERIODO_MEDICAO_001 { get; set; }
        public decimal? ICE_DENSIDADADE_RELATIVA_001 { get; set; }
        public decimal? ICE_CORRECAO_BSW_001 { get; set; }
        public decimal? ICE_CORRECAO_PRESSAO_LIQUIDO_001 { get; set; }
        public decimal? ICE_CRRCO_TEMPERATURA_LIQUIDO_001 { get; set; }
        public decimal? MED_PRESSAO_ESTATICA_001 { get; set; }
        public decimal? MED_TMPTA_FLUIDO_001 { get; set; }
        public decimal? MED_VOLUME_BRTO_CRRGO_MVMDO_001 { get; set; }
        public decimal? MED_VOLUME_BRUTO_MVMDO_001 { get; set; }
        public decimal? MED_VOLUME_LIQUIDO_MVMDO_001 { get; set; }
        public decimal? MED_VOLUME_TTLZO_FIM_PRDO_001 { get; set; }
        public decimal? MED_VOLUME_TTLZO_INCO_PRDO_001 { get; set; }
    }
}
