using PRIO.Models;

namespace PRIO.DTOS
{
    public class _002DTO : BaseModel
    {
        public string? NUM_SERIE_ELEMENTO_PRIMARIO_002 { get; set; }
        public int? COD_INSTALACAO_002 { get; set; }
        public string? COD_TAG_PONTO_MEDICAO_002 { get; set; }
        public string? NUM_SERIE_COMPUTADOR_VAZAO_002 { get; set; }
        public DateTime? DHA_COLETA_002 { get; set; }
        public double? MED_TEMPERATURA_1_002 { get; set; }
        public double? MED_PRESSAO_ATMSA_002 { get; set; }
        public double? MED_PRESSAO_RFRNA_002 { get; set; }
        public double? MED_DENSIDADE_RELATIVA_002 { get; set; }
        public string? DSC_NORMA_UTILIZADA_CALCULO_002 { get; set; }
        public double? PCT_CROMATOGRAFIA_NITROGENIO_002 { get; set; }
        public double? PCT_CROMATOGRAFIA_CO2_002 { get; set; }
        public double? PCT_CROMATOGRAFIA_METANO_002 { get; set; }
        public double? PCT_CROMATOGRAFIA_ETANO_002 { get; set; }
        public double? PCT_CROMATOGRAFIA_PROPANO_002 { get; set; }
        public double? PCT_CROMATOGRAFIA_N_BUTANO_002 { get; set; }
        public double? PCT_CROMATOGRAFIA_I_BUTANO_002 { get; set; }
        public double? PCT_CROMATOGRAFIA_N_PENTANO_002 { get; set; }
        public double? PCT_CROMATOGRAFIA_I_PENTANO_002 { get; set; }
        public double? PCT_CROMATOGRAFIA_HEXANO_002 { get; set; }
        public double? PCT_CROMATOGRAFIA_HEPTANO_002 { get; set; }
        public double? PCT_CROMATOGRAFIA_OCTANO_002 { get; set; }
        public double? PCT_CROMATOGRAFIA_NONANO_002 { get; set; }
        public double? PCT_CROMATOGRAFIA_DECANO_002 { get; set; }

        public double? PCT_CROMATOGRAFIA_H2S_002 { get; set; }
        public double? PCT_CROMATOGRAFIA_AGUA_002 { get; set; }
        public double? PCT_CROMATOGRAFIA_HELIO_002 { get; set; }
        public double? PCT_CROMATOGRAFIA_OXIGENIO_002 { get; set; }
        public double? PCT_CROMATOGRAFIA_CO_002 { get; set; }
        public double? PCT_CROMATOGRAFIA_HIDROGENIO_002 { get; set; }
        public double? PCT_CROMATOGRAFIA_ARGONIO_002 { get; set; }
        public string? DSC_VERSAO_SOFTWARE_002 { get; set; }
        public double? ICE_METER_FACTOR_1_002 { get; set; }
        public double? ICE_METER_FACTOR_2_002 { get; set; }
        public double? ICE_METER_FACTOR_3_002 { get; set; }
        public double? ICE_METER_FACTOR_4_002 { get; set; }
        public double? ICE_METER_FACTOR_5_002 { get; set; }
        public double? ICE_METER_FACTOR_6_002 { get; set; }
        public double? ICE_METER_FACTOR_7_002 { get; set; }
        public double? ICE_METER_FACTOR_8_002 { get; set; }
        public double? ICE_METER_FACTOR_9_002 { get; set; }
        public double? ICE_METER_FACTOR_10_002 { get; set; }
        public double? ICE_METER_FACTOR_11_002 { get; set; }
        public double? ICE_METER_FACTOR_12_002 { get; set; }
        public double? ICE_METER_FACTOR_13_002 { get; set; }
        public double? ICE_METER_FACTOR_14_002 { get; set; }
        public double? ICE_METER_FACTOR_15_002 { get; set; }
        public double? QTD_PULSOS_METER_FACTOR_1_002 { get; set; }
        public double? QTD_PULSOS_METER_FACTOR_2_002 { get; set; }
        public double? QTD_PULSOS_METER_FACTOR_3_002 { get; set; }
        public double? QTD_PULSOS_METER_FACTOR_4_002 { get; set; }
        public double? QTD_PULSOS_METER_FACTOR_5_002 { get; set; }
        public double? QTD_PULSOS_METER_FACTOR_6_002 { get; set; }
        public double? QTD_PULSOS_METER_FACTOR_7_002 { get; set; }
        public double? QTD_PULSOS_METER_FACTOR_8_002 { get; set; }
        public double? QTD_PULSOS_METER_FACTOR_9_002 { get; set; }
        public double? QTD_PULSOS_METER_FACTOR_10_002 { get; set; }
        public double? QTD_PULSOS_METER_FACTOR_11_002 { get; set; }
        public double? QTD_PULSOS_METER_FACTOR_12_002 { get; set; }
        public double? QTD_PULSOS_METER_FACTOR_13_002 { get; set; }
        public double? QTD_PULSOS_METER_FACTOR_14_002 { get; set; }
        public double? QTD_PULSOS_METER_FACTOR_15_002 { get; set; }

        public double? ICE_K_FACTOR_1_002 { get; set; }
        public double? ICE_K_FACTOR_2_002 { get; set; }
        public double? ICE_K_FACTOR_3_002 { get; set; }
        public double? ICE_K_FACTOR_4_002 { get; set; }
        public double? ICE_K_FACTOR_5_002 { get; set; }
        public double? ICE_K_FACTOR_6_002 { get; set; }
        public double? ICE_K_FACTOR_7_002 { get; set; }
        public double? ICE_K_FACTOR_8_002 { get; set; }
        public double? ICE_K_FACTOR_9_002 { get; set; }
        public double? ICE_K_FACTOR_10_002 { get; set; }
        public double? ICE_K_FACTOR_11_002 { get; set; }
        public double? ICE_K_FACTOR_12_002 { get; set; }
        public double? ICE_K_FACTOR_13_002 { get; set; }
        public double? ICE_K_FACTOR_14_002 { get; set; }
        public double? ICE_K_FACTOR_15_002 { get; set; }
        public double? QTD_PULSOS_K_FACTOR_1_002 { get; set; }
        public double? QTD_PULSOS_K_FACTOR_2_002 { get; set; }
        public double? QTD_PULSOS_K_FACTOR_3_002 { get; set; }
        public double? QTD_PULSOS_K_FACTOR_4_002 { get; set; }
        public double? QTD_PULSOS_K_FACTOR_5_002 { get; set; }
        public double? QTD_PULSOS_K_FACTOR_6_002 { get; set; }
        public double? QTD_PULSOS_K_FACTOR_7_002 { get; set; }
        public double? QTD_PULSOS_K_FACTOR_8_002 { get; set; }
        public double? QTD_PULSOS_K_FACTOR_9_002 { get; set; }
        public double? QTD_PULSOS_K_FACTOR_10_002 { get; set; }
        public double? QTD_PULSOS_K_FACTOR_11_002 { get; set; }
        public double? QTD_PULSOS_K_FACTOR_12_002 { get; set; }
        public double? QTD_PULSOS_K_FACTOR_13_002 { get; set; }
        public double? QTD_PULSOS_K_FACTOR_14_002 { get; set; }
        public double? QTD_PULSOS_K_FACTOR_15_002 { get; set; }
        public double? ICE_CUTOFF_002 { get; set; }
        public double? ICE_LIMITE_SPRR_ALARME_002 { get; set; }
        public double? ICE_LIMITE_INFRR_ALARME_002 { get; set; }

        public string? IND_HABILITACAO_ALARME_1_002 { get; set; }
        public string? NUM_SERIE_1_002 { get; set; }
        public double? MED_PRSO_LIMITE_SPRR_ALRME_002 { get; set; }
        public double? MED_PRSO_LMTE_INFRR_ALRME_002 { get; set; }
        public string? IND_HABILITACAO_ALARME_2_002 { get; set; }
        public double? MED_PRSO_ADOTADA_FALHA_002 { get; set; }
        public string? DSC_ESTADO_INSNO_CASO_FALHA_002 { get; set; }
        public string? IND_TIPO_PRESSAO_CONSIDERADA_002 { get; set; }
        public string? NUM_SERIE_2_002 { get; set; }
        public double? MED_TMPTA_SPRR_ALARME_002 { get; set; }
        public double? MED_TMPTA_INFRR_ALRME_002 { get; set; }
        public string? IND_HABILITACAO_ALARME_3_002 { get; set; }
        public double? MED_TMPTA_ADTTA_FALHA_002 { get; set; }
        public string? DSC_ESTADO_INSTRUMENTO_FALHA_002 { get; set; }
        public DateTime? DHA_INICIO_PERIODO_MEDICAO_002 { get; set; }
        public DateTime? DHA_FIM_PERIODO_MEDICAO_002 { get; set; }
        public double? ICE_DENSIDADE_RELATIVA_002 { get; set; }
        public double? MED_PRESSAO_ESTATICA_002 { get; set; }
        public double? MED_TEMPERATURA_2_002 { get; set; }
        public double? PRZ_DURACAO_FLUXO_EFETIVO_002 { get; set; }
        public double? MED_BRUTO_MOVIMENTADO_002 { get; set; }
        public double? MED_CORRIGIDO_MVMDO_002 { get; set; }
        public FileType? FileType { get; set; }

    }
}
