// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRIO.Data;

#nullable disable

namespace PRIO.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230519140756_UpdatingToDouble")]
    partial class UpdatingToDouble
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PRIO.Models.Bsw", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DHA_FALHA_BSW_039")
                        .HasColumnType("date");

                    b.Property<decimal?>("DHA_PCT_BSW_039")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("DHA_PCT_MAXIMO_BSW_039")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("MeasurementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementId");

                    b.ToTable("BSWS_039", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.Calibration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DHA_CERTIFICADO_ANTERIOR_039")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DHA_CERTIFICADO_ATUAL_039")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("DHA_FALHA_CALIBRACAO_039")
                        .HasColumnType("date");

                    b.Property<decimal?>("DHA_NUM_FATOR_CALIBRACAO_ANTERIOR_039")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("DHA_NUM_FATOR_CALIBRACAO_ATUAL_039")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("MeasurementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementId");

                    b.ToTable("Calibrations_039", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.Cluster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.HasIndex("UserId");

                    b.ToTable("Clusters", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.Completion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.Property<Guid>("ReservoirId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReservoirId");

                    b.HasIndex("UserId");

                    b.ToTable("Completions", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.Field", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("APIGradeOil")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL");

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Basin")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<decimal>("CalorificPowerGas")
                        .HasPrecision(8, 2)
                        .HasColumnType("DECIMAL");

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodField")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("Commerciality")
                        .HasColumnType("DATE");

                    b.Property<string>("ContractNum")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("ContractOperator")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("ContractTypeDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CorrectedArea")
                        .HasPrecision(6, 2)
                        .HasColumnType("DECIMAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DiscoveryDate")
                        .HasColumnType("DATE");

                    b.Property<string>("EnviromentDepth")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("MainFluid")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("PreSaltWells")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProductionBeginning")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("ProductionFinishDate")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("ProductionFinishForecast")
                        .HasColumnType("DATE");

                    b.Property<int>("QtdWells")
                        .HasColumnType("int");

                    b.Property<string>("Round")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("RoundDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Situation")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("WaterDepth")
                        .HasPrecision(6, 2)
                        .HasColumnType("DECIMAL");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId");

                    b.HasIndex("UserId");

                    b.ToTable("Fields", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.FileType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("QtdColumns")
                        .HasColumnType("int");

                    b.Property<string>("Structure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FileTypes", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.Installation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("BeginningValidity")
                        .HasColumnType("DATE");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("CodInstallation")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FieldService")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<decimal>("GasProcessing")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL");

                    b.Property<DateTime>("InclusionDate")
                        .HasColumnType("DATE");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<decimal>("OilProcessing")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("PsmQty")
                        .HasColumnType("int");

                    b.Property<bool>("Situation")
                        .HasColumnType("bit");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("WaterDepth")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("UserId");

                    b.ToTable("Installations", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.Measurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("CE_LIMITE_SPRR_ALARME_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<string>("COD_CADASTRO_POCO_042")
                        .HasMaxLength(12)
                        .HasColumnType("varchar");

                    b.Property<string>("COD_FALHA_039")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<string>("COD_FALHA_SUPERIOR_039")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<int?>("COD_INSTALACAO_001")
                        .HasColumnType("int");

                    b.Property<int?>("COD_INSTALACAO_002")
                        .HasColumnType("int");

                    b.Property<int?>("COD_INSTALACAO_003")
                        .HasColumnType("int");

                    b.Property<int?>("COD_INSTALACAO_040")
                        .HasColumnType("int");

                    b.Property<int?>("COD_INSTALACAO_041")
                        .HasColumnType("int");

                    b.Property<int?>("COD_INSTALACAO_042")
                        .HasColumnType("int");

                    b.Property<int?>("COD_INSTALACAO_045")
                        .HasColumnType("int");

                    b.Property<string>("COD_TAG_EQUIPAMENTO_039")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<string>("COD_TAG_PONTO_MEDICAO_001")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<string>("COD_TAG_PONTO_MEDICAO_002")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<short?>("COD_TAG_PONTO_MEDICAO_003")
                        .HasColumnType("smallint");

                    b.Property<string>("COD_TAG_PONTO_MEDICAO_040")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<string>("COD_TAG_PONTO_MEDICAO_041")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<string>("COD_TAG_PONTO_MEDICAO_045")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<string>("COD_TAG_PONTO_MEDICAO_GAS_042")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<string>("COD_TAG_PONTO_MEDICAO_OLEO_042")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DHA_APLICACAO_042")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DHA_ATUALIZACAO_041")
                        .HasColumnType("date");

                    b.Property<int?>("DHA_COD_INSTALACAO_039")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DHA_COLETA_001")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("DHA_COLETA_002")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal");

                    b.Property<DateTime?>("DHA_COLETA_003")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DHA_DETECCAO_039")
                        .HasColumnType("datetime");

                    b.Property<string>("DHA_DSC_ACAO_039")
                        .HasColumnType("text");

                    b.Property<string>("DHA_DSC_FALHA_039")
                        .HasColumnType("text");

                    b.Property<string>("DHA_DSC_METODOLOGIA_039")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DHA_FIM_PERIODO_MEDICAO_001")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DHA_FIM_PERIODO_MEDICAO_002")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DHA_FIM_PERIODO_MEDICAO_003")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DHA_INICIO_PERIODO_MEDICAO_001")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DHA_INICIO_PERIODO_MEDICAO_002")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DHA_INICIO_PERIODO_MEDICAO_003")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DHA_MEDICAO_040")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DHA_MEDICAO_045")
                        .HasColumnType("datetime");

                    b.Property<string>("DHA_NOM_RESPONSAVEL_RELATO_039")
                        .HasMaxLength(155)
                        .HasColumnType("varchar");

                    b.Property<short?>("DHA_NUM_PREVISAO_RETORNO_DIAS_039")
                        .HasColumnType("smallint");

                    b.Property<string>("DHA_NUM_SERIE_EQUIPAMENTO_039")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("DHA_OCORRENCIA_039")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DHA_RETORNO_039")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DHA_TESTE_042")
                        .HasColumnType("datetime");

                    b.Property<string>("DSC_ESTADO_INSNO_CASO_FALHA_001")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_ESTADO_INSNO_CASO_FALHA_002")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_ESTADO_INSNO_CASO_FALHA_1_003")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_ESTADO_INSNO_CASO_FALHA_2_003")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_ESTADO_INSNO_CASO_FALHA_3_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_ESTADO_INSTRUMENTO_FALHA_002")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_ESTADO_INSTRUMENTO_FALHA_003")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_ESTADO_INSTRUMENTO_FALHA_1_001")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_ESTADO_INSTRUMENTO_FALHA_2_001")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_ESTADO_INSTRUMENTO_FALHA_3_001")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_LCLZO_TMDA_PRSO_DFRNL_003")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_MATERIAL_CNSTO_TRCHO_MDCO_003")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_MATERIAL_CONTRUCAO_PLACA_003")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_NORMA_UTILIZADA_CALCULO_002")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_NORMA_UTILIZADA_CALCULO_003")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<short?>("DSC_TIPO_FALHA_039")
                        .HasColumnType("smallint");

                    b.Property<string>("DSC_VERSAO_SOFTWARE_001")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_VERSAO_SOFTWARE_002")
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_VERSAO_SOFTWARE_003")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<Guid?>("FileTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ICE_CORRECAO_BSW_001")
                        .HasPrecision(8, 8)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_CORRECAO_PRESSAO_LIQUIDO_001")
                        .HasPrecision(8, 8)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_CRRCO_TEMPERATURA_LIQUIDO_001")
                        .HasPrecision(8, 8)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_CUTOFF_001")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_CUTOFF_002")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_DENSIDADADE_RELATIVA_001")
                        .HasPrecision(8, 8)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_DENSIDADE_RELATIVA_002")
                        .HasPrecision(8, 8)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_DENSIDADE_RELATIVA_003")
                        .HasPrecision(8, 8)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_10_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_10_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_11_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_11_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_12_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_12_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_13_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_13_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_14_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_14_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_15_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_15_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_1_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_1_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_2_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_2_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_3_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_3_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_4_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_4_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_5_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_5_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_6_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_6_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_7_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_7_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_8_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_8_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_9_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_K_FACTOR_9_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_LIMITE_INFRR_ALARME_001")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_LIMITE_INFRR_ALARME_002")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_LIMITE_INFRR_ALARME_1_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<bool?>("ICE_LIMITE_INFRR_ALARME_2_003")
                        .HasColumnType("bit");

                    b.Property<decimal?>("ICE_LIMITE_SPRR_ALARME_001")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_LIMITE_SPRR_ALARME_002")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_10_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_10_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_11_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_11_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_12_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_12_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_13_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_13_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_14_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_14_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_15_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_15_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_1_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_1_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_2_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_2_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_3_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_3_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_4_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_4_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_5_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_5_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_6_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_6_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_7_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_7_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_8_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_8_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_9_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("ICE_METER_FACTOR_9_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<bool?>("IND_HABILITACAO_ALARME_1_001")
                        .HasColumnType("bit");

                    b.Property<bool?>("IND_HABILITACAO_ALARME_1_002")
                        .HasColumnType("bit");

                    b.Property<bool?>("IND_HABILITACAO_ALARME_1_003")
                        .HasColumnType("bit");

                    b.Property<bool?>("IND_HABILITACAO_ALARME_2_001")
                        .HasColumnType("bit");

                    b.Property<bool?>("IND_HABILITACAO_ALARME_2_002")
                        .HasColumnType("bit");

                    b.Property<bool?>("IND_HABILITACAO_ALARME_2_003")
                        .HasColumnType("bit");

                    b.Property<bool?>("IND_HABILITACAO_ALARME_3_001")
                        .HasColumnType("bit");

                    b.Property<bool?>("IND_HABILITACAO_ALARME_3_002")
                        .HasColumnType("bit");

                    b.Property<bool?>("IND_HABILITACAO_ALARME_3_003")
                        .HasColumnType("bit");

                    b.Property<bool?>("IND_HABILITACAO_ALARME_4_001")
                        .HasColumnType("bit");

                    b.Property<bool?>("IND_HABILITACAO_ALARME_4_003")
                        .HasColumnType("bit");

                    b.Property<bool?>("IND_HABILITACAO_ALARME_5_001")
                        .HasColumnType("bit");

                    b.Property<bool?>("IND_HABILITACAO_ALARME_5_003")
                        .HasColumnType("bit");

                    b.Property<bool?>("IND_NAVIO_045")
                        .HasColumnType("bit");

                    b.Property<string>("IND_TIPO_NOTIFICACAO_039")
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("IND_TIPO_PRESSAO_CONSIDERADA_001")
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("IND_TIPO_PRESSAO_CONSIDERADA_002")
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("IND_TIPO_PRESSAO_CONSIDERADA_003")
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("IND_TIPO_TESTE_042")
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("IND_TOMADA_PRESSAO_ESTATICA_003")
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<bool?>("IND_USER_CALCULO_040")
                        .HasColumnType("bit");

                    b.Property<bool?>("IND_VALIDO_042")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MED_BRUTO_MOVIMENTADO_002")
                        .HasPrecision(6, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_CAPACIDADE_BRUTA_045")
                        .HasPrecision(7, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_CAPACIDADE_CORRIGIDA_045")
                        .HasPrecision(7, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_CAPACIDADE_LIQUIDA_045")
                        .HasPrecision(7, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_CORRIGIDO_MVMDO_002")
                        .HasPrecision(6, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_CORRIGIDO_MVMDO_003")
                        .HasPrecision(6, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_CUTOFF_KPA_1_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_CUTOFF_KPA_2_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_DENSIDADE_RELATIVA_001")
                        .HasPrecision(8, 8)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_DENSIDADE_RELATIVA_002")
                        .HasPrecision(8, 8)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_DENSIDADE_RELATIVA_003")
                        .HasPrecision(8, 8)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_DIAMETRO_REFERENCIA_003")
                        .HasPrecision(4, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_DIFERENCIAL_PRESSAO_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_DMTRO_INTRO_TRCHO_MDCO_003")
                        .HasPrecision(4, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_POTENCIAL_AGUA_042")
                        .HasPrecision(8, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_POTENCIAL_GAS_042")
                        .HasPrecision(8, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_POTENCIAL_OLEO_042")
                        .HasPrecision(8, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRESSAO_ATMSA_001")
                        .HasPrecision(3, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRESSAO_ATMSA_002")
                        .HasPrecision(3, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRESSAO_ATMSA_003")
                        .HasPrecision(3, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRESSAO_ESTATICA_001")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRESSAO_ESTATICA_002")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRESSAO_ESTATICA_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRESSAO_RFRNA_001")
                        .HasPrecision(3, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRESSAO_RFRNA_002")
                        .HasPrecision(3, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRESSAO_RFRNA_003")
                        .HasPrecision(3, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRSO_ADOTADA_FALHA_001")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRSO_ADOTADA_FALHA_002")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRSO_ADOTADA_FALHA_1_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRSO_ADOTADA_FALHA_2_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRSO_ADOTADA_FALHA_3_003")
                        .HasMaxLength(50)
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRSO_LIMITE_SPRR_ALRME_001")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRSO_LIMITE_SPRR_ALRME_002")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRSO_LIMITE_SPRR_ALRME_1_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRSO_LIMITE_SPRR_ALRME_2_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRSO_LIMITE_SPRR_ALRME_3_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRSO_LIMITE_SPRR_ALRME_4_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRSO_LIMITE_SPRR_ALRME_5_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRSO_LMTE_INFRR_ALRME_001")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRSO_LMTE_INFRR_ALRME_002")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRSO_LMTE_INFRR_ALRME_1_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRSO_LMTE_INFRR_ALRME_2_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRSO_LMTE_INFRR_ALRME_3_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRSO_LMTE_INFRR_ALRME_4_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_PRSO_LMTE_INFRR_ALRME_5_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_TEMPERATURA_001")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_TEMPERATURA_1_002")
                        .HasPrecision(3, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_TEMPERATURA_1_003")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_TEMPERATURA_2_002")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_TEMPERATURA_2_003")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_TEMPERATURA_RFRNA_003")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_TMPTA_ADTTA_FALHA_001")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_TMPTA_ADTTA_FALHA_002")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_TMPTA_ADTTA_FALHA_003")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_TMPTA_FLUIDO_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_TMPTA_INFRR_ALRME_001")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_TMPTA_INFRR_ALRME_002")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_TMPTA_INFRR_ALRME_003")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_TMPTA_SPRR_ALARME_001")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_TMPTA_SPRR_ALARME_002")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_TMPTA_SPRR_ALARME_003")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_TMPTA_TRCHO_MDCO_003")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_VAZAO_AGUA_042")
                        .HasPrecision(8, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_VAZAO_GAS_042")
                        .HasPrecision(8, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_VAZAO_OLEO_042")
                        .HasPrecision(8, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_VOLUME_BRTO_CRRGO_MVMDO_001")
                        .HasPrecision(6, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_VOLUME_BRUTO_MVMDO_001")
                        .HasPrecision(6, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_VOLUME_LIQUIDO_MVMDO_001")
                        .HasPrecision(6, 5)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_VOLUME_TTLZO_FIM_PRDO_001")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("MED_VOLUME_TTLZO_INCO_PRDO_001")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal");

                    b.Property<string>("NOM_BOLETIM_ANALISE_040")
                        .HasMaxLength(120)
                        .HasColumnType("varchar");

                    b.Property<string>("NOM_BOLETIM_ANALISE_041")
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("NOM_RELATORIO_042")
                        .HasPrecision(40)
                        .HasColumnType("varchar");

                    b.Property<string>("NOM_RELATORIO_BSW_042")
                        .HasMaxLength(40)
                        .HasColumnType("varchar");

                    b.Property<string>("NOM_RELATORIO_BSW_045")
                        .HasMaxLength(40)
                        .HasColumnType("varchar");

                    b.Property<string>("NOM_RELATORIO_FATOR_ENCLO_042")
                        .HasMaxLength(40)
                        .HasColumnType("varchar");

                    b.Property<string>("NOM_RELATORIO_RZO_SOLUBILIDADE_042")
                        .HasMaxLength(40)
                        .HasColumnType("varchar");

                    b.Property<decimal?>("NUM_FATOR_ENCOLHIMENTO_041")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal(6,6)");

                    b.Property<decimal?>("NUM_FATOR_ENCOLHIMENTO_042")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<string>("NUM_SERIE_045")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_1_001")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_1_002")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_1_003")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_2_001")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_2_002")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_2_003")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_3_001")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_3_003")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_4_001")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_4_003")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_5_003")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_6_003")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_COMPUTADOR_VAZAO_001")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_COMPUTADOR_VAZAO_002")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_COMPUTADOR_VAZAO_003")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_ELEMENTO_PRIMARIO_001")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_ELEMENTO_PRIMARIO_002")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_ELEMENTO_PRIMARIO_003")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<decimal?>("PCT_ADOTADO_CASO_FALHA_1_001")
                        .HasPrecision(3, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_ADOTADO_CASO_FALHA_2_001")
                        .HasPrecision(3, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_BSW_040")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal?>("PCT_BSW_042")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_AGUA_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_AGUA_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_ARGONIO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_ARGONIO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_CO2_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_CO2_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_CO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_CO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_DECANO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_DECANO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_ETANO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_ETANO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_H2S_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_H2S_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_HELIO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_HELIO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_HEPTANO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_HEPTANO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_HEXANO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_HEXANO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_HIDROGENIO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_HIDROGENIO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_I_BUTANO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_I_BUTANO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_I_PENTANO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_I_PENTANO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_METANO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_METANO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_NITROGENIO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_NITROGENIO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_NONANO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_NONANO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_N_BUTANO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_N_BUTANO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_N_PENTANO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_N_PENTANO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_OCTANO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_OCTANO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_OXIGENIO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_OXIGENIO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_PROPANO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_CROMATOGRAFIA_PROPANO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_LIMITE_INFERIOR_1_001")
                        .HasPrecision(3, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_LIMITE_INFERIOR_2_001")
                        .HasPrecision(3, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_LIMITE_SUPERIOR_1_001")
                        .HasPrecision(3, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_LIMITE_SUPERIOR_2_001")
                        .HasPrecision(3, 3)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PCT_MAXIMO_BSW_040")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal?>("PCT_RAZAO_SOLUBILIDADE_042")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PRZ_DURACAO_FLUXO_EFETIVO_002")
                        .HasPrecision(4, 4)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("PRZ_DURACAO_FLUXO_EFETIVO_003")
                        .HasPrecision(4, 4)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_10_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_10_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_11_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_11_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_12_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_12_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_13_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_13_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_14_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_14_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_15_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_15_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_1_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_1_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_2_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_2_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_3_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_3_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_4_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_4_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_5_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_5_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_6_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_6_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_7_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_7_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_8_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_8_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_9_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_K_FACTOR_9_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_10_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_10_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_11_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_11_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_12_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_12_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_13_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_13_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_14_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_14_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_15_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_15_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_1_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_1_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_2_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_2_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_3_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_3_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_4_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_4_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_5_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_5_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_6_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_6_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_7_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_7_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_8_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_8_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_9_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("QTD_PULSOS_METER_FACTOR_9_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal");

                    b.Property<string>("TAG_TANQUE_045")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FileTypeId");

                    b.ToTable("Measurements", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.Reservoir", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservoirs", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresIn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("UserHttpAgent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Units", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.Volume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DHA_MEDICAO_039")
                        .HasColumnType("date");

                    b.Property<decimal?>("DHA_MED_DECLARADO_039")
                        .HasPrecision(7, 6)
                        .HasColumnType("decimal");

                    b.Property<decimal?>("DHA_MED_REGISTRADO_039")
                        .HasPrecision(7, 6)
                        .HasColumnType("decimal");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("MeasurementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementId");

                    b.ToTable("Volumes_039", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.Well", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArtificialElevation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("BaseOfPerforated")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Basin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Block")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("ClusterName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("CodInstallation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("CompanyCodOperator")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("CompletionDate")
                        .HasColumnType("DATE");

                    b.Property<Guid>("CompletionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompletionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("CoordX")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("CoordY")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("CurrentSituation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("DrillingFinishDate")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("DrillingStartDate")
                        .HasColumnType("DATE");

                    b.Property<string>("EnviromentProduction")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("FieldCod")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("InstallationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("MD")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("NameAnp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("ProductionByReservoir")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("RegisterNum")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("ReservoirName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<decimal>("SounderDepth")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("TVD")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("TopOfPerforated")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("WaterDepth")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL");

                    b.Property<string>("WellOperatorName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("CompletionId");

                    b.HasIndex("UserId");

                    b.ToTable("Wells", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.Bsw", b =>
                {
                    b.HasOne("PRIO.Models.Measurement", "Measurement")
                        .WithMany("LISTA_BSW")
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("PRIO.Models.Calibration", b =>
                {
                    b.HasOne("PRIO.Models.Measurement", "Measurement")
                        .WithMany("LISTA_CALIBRACAO")
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("PRIO.Models.Cluster", b =>
                {
                    b.HasOne("PRIO.Models.Unit", "Unit")
                        .WithMany("Clusters")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRIO.Models.User", "User")
                        .WithMany("Clusters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Unit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRIO.Models.Completion", b =>
                {
                    b.HasOne("PRIO.Models.Reservoir", "Reservoir")
                        .WithMany("Completions")
                        .HasForeignKey("ReservoirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRIO.Models.User", "User")
                        .WithMany("Completions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Reservoir");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRIO.Models.Field", b =>
                {
                    b.HasOne("PRIO.Models.Cluster", "Cluster")
                        .WithMany("Fields")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRIO.Models.User", "User")
                        .WithMany("Fields")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Cluster");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRIO.Models.Installation", b =>
                {
                    b.HasOne("PRIO.Models.Field", "Field")
                        .WithMany("Installations")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRIO.Models.User", "User")
                        .WithMany("Installations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Field");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRIO.Models.Measurement", b =>
                {
                    b.HasOne("PRIO.Models.FileType", "FileType")
                        .WithMany("Measurements")
                        .HasForeignKey("FileTypeId");

                    b.Navigation("FileType");
                });

            modelBuilder.Entity("PRIO.Models.Reservoir", b =>
                {
                    b.HasOne("PRIO.Models.Installation", "Installation")
                        .WithMany("Reservoirs")
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRIO.Models.User", "User")
                        .WithMany("Reservoirs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Installation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRIO.Models.Session", b =>
                {
                    b.HasOne("PRIO.Models.User", "User")
                        .WithOne("Session")
                        .HasForeignKey("PRIO.Models.Session", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRIO.Models.Unit", b =>
                {
                    b.HasOne("PRIO.Models.User", "User")
                        .WithMany("Units")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRIO.Models.Volume", b =>
                {
                    b.HasOne("PRIO.Models.Measurement", "Measurement")
                        .WithMany("LISTA_VOLUME")
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("PRIO.Models.Well", b =>
                {
                    b.HasOne("PRIO.Models.Completion", "Completion")
                        .WithMany("Wells")
                        .HasForeignKey("CompletionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRIO.Models.User", "User")
                        .WithMany("Wells")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Completion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRIO.Models.Cluster", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("PRIO.Models.Completion", b =>
                {
                    b.Navigation("Wells");
                });

            modelBuilder.Entity("PRIO.Models.Field", b =>
                {
                    b.Navigation("Installations");
                });

            modelBuilder.Entity("PRIO.Models.FileType", b =>
                {
                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("PRIO.Models.Installation", b =>
                {
                    b.Navigation("Reservoirs");
                });

            modelBuilder.Entity("PRIO.Models.Measurement", b =>
                {
                    b.Navigation("LISTA_BSW");

                    b.Navigation("LISTA_CALIBRACAO");

                    b.Navigation("LISTA_VOLUME");
                });

            modelBuilder.Entity("PRIO.Models.Reservoir", b =>
                {
                    b.Navigation("Completions");
                });

            modelBuilder.Entity("PRIO.Models.Unit", b =>
                {
                    b.Navigation("Clusters");
                });

            modelBuilder.Entity("PRIO.Models.User", b =>
                {
                    b.Navigation("Clusters");

                    b.Navigation("Completions");

                    b.Navigation("Fields");

                    b.Navigation("Installations");

                    b.Navigation("Reservoirs");

                    b.Navigation("Session");

                    b.Navigation("Units");

                    b.Navigation("Wells");
                });
#pragma warning restore 612, 618
        }
    }
}
