// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRIO.Data;

#nullable disable

namespace PRIO.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230601173017_addColumnCodWellInWell")]
    partial class addColumnCodWellInWell
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PRIO.Models.Cluster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodCluster")
                        .HasMaxLength(60)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Clusters", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.Completion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodCompletion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR");

                    b.Property<Guid?>("ReservoirId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WellId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReservoirId");

                    b.HasIndex("UserId");

                    b.HasIndex("WellId");

                    b.ToTable("Completions", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.Field", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Basin")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("CodField")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId");

                    b.HasIndex("UserId");

                    b.ToTable("Fields", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.FileType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FileTypes", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.Installation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClusterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodInstallation")
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId");

                    b.HasIndex("UserId");

                    b.ToTable("Installations", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.Measurements.Bsw", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DHA_FALHA_BSW_039")
                        .HasColumnType("date");

                    b.Property<double>("DHA_PCT_BSW_039")
                        .HasPrecision(3, 2)
                        .HasColumnType("float");

                    b.Property<double>("DHA_PCT_MAXIMO_BSW_039")
                        .HasPrecision(3, 2)
                        .HasColumnType("float");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("MeasurementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementId");

                    b.ToTable("BSWS_039", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.Measurements.Calibration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DHA_CERTIFICADO_ANTERIOR_039")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DHA_CERTIFICADO_ATUAL_039")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("DHA_FALHA_CALIBRACAO_039")
                        .HasColumnType("date");

                    b.Property<double?>("DHA_NUM_FATOR_CALIBRACAO_ANTERIOR_039")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("DHA_NUM_FATOR_CALIBRACAO_ATUAL_039")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("MeasurementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementId");

                    b.ToTable("Calibrations_039", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.Measurements.Measurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("CE_LIMITE_SPRR_ALARME_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<string>("COD_FALHA_039")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<string>("COD_FALHA_SUPERIOR_039")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<string>("COD_INSTALACAO_001")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<string>("COD_INSTALACAO_002")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<string>("COD_INSTALACAO_003")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<string>("COD_TAG_EQUIPAMENTO_039")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<string>("COD_TAG_PONTO_MEDICAO_001")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<string>("COD_TAG_PONTO_MEDICAO_002")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<string>("COD_TAG_PONTO_MEDICAO_003")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DHA_COD_INSTALACAO_039")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("DHA_COLETA_001")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DHA_COLETA_002")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DHA_COLETA_003")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DHA_DETECCAO_039")
                        .HasColumnType("datetime");

                    b.Property<string>("DHA_DSC_ACAO_039")
                        .HasColumnType("text");

                    b.Property<string>("DHA_DSC_FALHA_039")
                        .HasColumnType("text");

                    b.Property<string>("DHA_DSC_METODOLOGIA_039")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DHA_FIM_PERIODO_MEDICAO_001")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DHA_FIM_PERIODO_MEDICAO_002")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DHA_FIM_PERIODO_MEDICAO_003")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DHA_INICIO_PERIODO_MEDICAO_001")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DHA_INICIO_PERIODO_MEDICAO_002")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DHA_INICIO_PERIODO_MEDICAO_003")
                        .HasColumnType("datetime");

                    b.Property<string>("DHA_NOM_RESPONSAVEL_RELATO_039")
                        .HasMaxLength(155)
                        .HasColumnType("varchar");

                    b.Property<string>("DHA_NUM_PREVISAO_RETORNO_DIAS_039")
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.Property<string>("DHA_NUM_SERIE_EQUIPAMENTO_039")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("DHA_OCORRENCIA_039")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DHA_RETORNO_039")
                        .HasColumnType("datetime");

                    b.Property<string>("DSC_ESTADO_INSNO_CASO_FALHA_001")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_ESTADO_INSNO_CASO_FALHA_002")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_ESTADO_INSNO_CASO_FALHA_1_003")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_ESTADO_INSNO_CASO_FALHA_2_003")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_ESTADO_INSNO_CASO_FALHA_3_003")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_ESTADO_INSTRUMENTO_FALHA_002")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_ESTADO_INSTRUMENTO_FALHA_003")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_ESTADO_INSTRUMENTO_FALHA_1_001")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_ESTADO_INSTRUMENTO_FALHA_2_001")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_ESTADO_INSTRUMENTO_FALHA_3_001")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_LCLZO_TMDA_PRSO_DFRNL_003")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_MATERIAL_CNSTO_TRCHO_MDCO_003")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_MATERIAL_CONTRUCAO_PLACA_003")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_NORMA_UTILIZADA_CALCULO_002")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_NORMA_UTILIZADA_CALCULO_003")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<short?>("DSC_TIPO_FALHA_039")
                        .HasColumnType("smallint");

                    b.Property<string>("DSC_VERSAO_SOFTWARE_001")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_VERSAO_SOFTWARE_002")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("DSC_VERSAO_SOFTWARE_003")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FileTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("ICE_CORRECAO_BSW_001")
                        .HasPrecision(8, 8)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_CORRECAO_PRESSAO_LIQUIDO_001")
                        .HasPrecision(8, 8)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_CRRCO_TEMPERATURA_LIQUIDO_001")
                        .HasPrecision(8, 8)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_CUTOFF_001")
                        .HasPrecision(6, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_CUTOFF_002")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_DENSIDADADE_RELATIVA_001")
                        .HasPrecision(8, 8)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_DENSIDADE_RELATIVA_002")
                        .HasPrecision(8, 8)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_DENSIDADE_RELATIVA_003")
                        .HasPrecision(8, 8)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_10_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_10_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_11_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_11_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_12_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_12_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_13_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_13_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_14_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_14_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_15_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_15_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_1_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_1_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_2_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_2_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_3_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_3_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_4_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_4_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_5_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_5_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_6_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_6_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_7_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_7_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_8_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_8_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_9_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_K_FACTOR_9_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_LIMITE_INFRR_ALARME_001")
                        .HasPrecision(6, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_LIMITE_INFRR_ALARME_002")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_LIMITE_INFRR_ALARME_1_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<bool?>("ICE_LIMITE_INFRR_ALARME_2_003")
                        .HasColumnType("bit");

                    b.Property<double?>("ICE_LIMITE_SPRR_ALARME_001")
                        .HasPrecision(6, 2)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_LIMITE_SPRR_ALARME_002")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_10_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_10_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_11_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_11_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_12_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_12_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_13_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_13_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_14_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_14_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_15_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_15_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_1_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_1_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_2_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_2_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_3_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_3_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_4_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_4_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_5_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_5_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_6_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_6_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_7_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_7_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_8_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_8_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_9_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("ICE_METER_FACTOR_9_002")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<string>("IND_HABILITACAO_ALARME_1_001")
                        .HasMaxLength(1)
                        .HasColumnType("varchar");

                    b.Property<string>("IND_HABILITACAO_ALARME_1_002")
                        .HasMaxLength(1)
                        .HasColumnType("varchar");

                    b.Property<string>("IND_HABILITACAO_ALARME_1_003")
                        .HasMaxLength(1)
                        .HasColumnType("varchar");

                    b.Property<string>("IND_HABILITACAO_ALARME_2_001")
                        .HasMaxLength(1)
                        .HasColumnType("varchar");

                    b.Property<string>("IND_HABILITACAO_ALARME_2_002")
                        .HasMaxLength(1)
                        .HasColumnType("varchar");

                    b.Property<string>("IND_HABILITACAO_ALARME_2_003")
                        .HasMaxLength(1)
                        .HasColumnType("varchar");

                    b.Property<string>("IND_HABILITACAO_ALARME_3_001")
                        .HasMaxLength(1)
                        .HasColumnType("varchar");

                    b.Property<string>("IND_HABILITACAO_ALARME_3_002")
                        .HasMaxLength(1)
                        .HasColumnType("varchar");

                    b.Property<string>("IND_HABILITACAO_ALARME_3_003")
                        .HasMaxLength(1)
                        .HasColumnType("varchar");

                    b.Property<string>("IND_HABILITACAO_ALARME_4_001")
                        .HasMaxLength(1)
                        .HasColumnType("varchar");

                    b.Property<string>("IND_HABILITACAO_ALARME_4_003")
                        .HasMaxLength(1)
                        .HasColumnType("varchar");

                    b.Property<string>("IND_HABILITACAO_ALARME_5_001")
                        .HasMaxLength(1)
                        .HasColumnType("varchar");

                    b.Property<string>("IND_HABILITACAO_ALARME_5_003")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IND_TIPO_NOTIFICACAO_039")
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("IND_TIPO_PRESSAO_CONSIDERADA_001")
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("IND_TIPO_PRESSAO_CONSIDERADA_002")
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("IND_TIPO_PRESSAO_CONSIDERADA_003")
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<string>("IND_TOMADA_PRESSAO_ESTATICA_003")
                        .HasMaxLength(1)
                        .HasColumnType("char");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double?>("MED_BRUTO_MOVIMENTADO_002")
                        .HasPrecision(6, 5)
                        .HasColumnType("float");

                    b.Property<double?>("MED_CORRIGIDO_MVMDO_002")
                        .HasPrecision(6, 5)
                        .HasColumnType("float");

                    b.Property<double?>("MED_CORRIGIDO_MVMDO_003")
                        .HasPrecision(6, 5)
                        .HasColumnType("float");

                    b.Property<double?>("MED_CUTOFF_KPA_1_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_CUTOFF_KPA_2_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_DENSIDADE_RELATIVA_001")
                        .HasPrecision(8, 8)
                        .HasColumnType("float");

                    b.Property<double?>("MED_DENSIDADE_RELATIVA_002")
                        .HasPrecision(8, 8)
                        .HasColumnType("float");

                    b.Property<double?>("MED_DENSIDADE_RELATIVA_003")
                        .HasPrecision(8, 8)
                        .HasColumnType("float");

                    b.Property<double?>("MED_DIAMETRO_REFERENCIA_003")
                        .HasPrecision(4, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_DIFERENCIAL_PRESSAO_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_DMTRO_INTRO_TRCHO_MDCO_003")
                        .HasPrecision(4, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRESSAO_ATMSA_001")
                        .HasPrecision(3, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRESSAO_ATMSA_002")
                        .HasPrecision(3, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRESSAO_ATMSA_003")
                        .HasPrecision(3, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRESSAO_ESTATICA_001")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRESSAO_ESTATICA_002")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRESSAO_ESTATICA_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRESSAO_RFRNA_001")
                        .HasPrecision(3, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRESSAO_RFRNA_002")
                        .HasPrecision(3, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRESSAO_RFRNA_003")
                        .HasPrecision(3, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRSO_ADOTADA_FALHA_001")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRSO_ADOTADA_FALHA_002")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRSO_ADOTADA_FALHA_1_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRSO_ADOTADA_FALHA_2_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRSO_ADOTADA_FALHA_3_003")
                        .HasMaxLength(50)
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRSO_LIMITE_SPRR_ALRME_001")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRSO_LIMITE_SPRR_ALRME_002")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRSO_LIMITE_SPRR_ALRME_1_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRSO_LIMITE_SPRR_ALRME_2_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRSO_LIMITE_SPRR_ALRME_3_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRSO_LIMITE_SPRR_ALRME_4_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRSO_LIMITE_SPRR_ALRME_5_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRSO_LMTE_INFRR_ALRME_001")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRSO_LMTE_INFRR_ALRME_002")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRSO_LMTE_INFRR_ALRME_1_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRSO_LMTE_INFRR_ALRME_2_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRSO_LMTE_INFRR_ALRME_3_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRSO_LMTE_INFRR_ALRME_4_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_PRSO_LMTE_INFRR_ALRME_5_003")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_TEMPERATURA_001")
                        .HasPrecision(3, 2)
                        .HasColumnType("float");

                    b.Property<double?>("MED_TEMPERATURA_1_002")
                        .HasPrecision(3, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_TEMPERATURA_1_003")
                        .HasPrecision(3, 2)
                        .HasColumnType("float");

                    b.Property<double?>("MED_TEMPERATURA_2_002")
                        .HasPrecision(3, 2)
                        .HasColumnType("float");

                    b.Property<double?>("MED_TEMPERATURA_2_003")
                        .HasPrecision(3, 2)
                        .HasColumnType("float");

                    b.Property<double?>("MED_TEMPERATURA_RFRNA_003")
                        .HasPrecision(3, 2)
                        .HasColumnType("float");

                    b.Property<double?>("MED_TMPTA_ADTTA_FALHA_001")
                        .HasPrecision(3, 2)
                        .HasColumnType("float");

                    b.Property<double?>("MED_TMPTA_ADTTA_FALHA_002")
                        .HasPrecision(3, 2)
                        .HasColumnType("float");

                    b.Property<double?>("MED_TMPTA_ADTTA_FALHA_003")
                        .HasPrecision(3, 2)
                        .HasColumnType("float");

                    b.Property<double?>("MED_TMPTA_FLUIDO_001")
                        .HasPrecision(5, 5)
                        .HasColumnType("float");

                    b.Property<double?>("MED_TMPTA_INFRR_ALRME_001")
                        .HasPrecision(3, 2)
                        .HasColumnType("float");

                    b.Property<double?>("MED_TMPTA_INFRR_ALRME_002")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_TMPTA_INFRR_ALRME_003")
                        .HasPrecision(3, 2)
                        .HasColumnType("float");

                    b.Property<double?>("MED_TMPTA_SPRR_ALARME_001")
                        .HasPrecision(3, 2)
                        .HasColumnType("float");

                    b.Property<double?>("MED_TMPTA_SPRR_ALARME_002")
                        .HasPrecision(6, 3)
                        .HasColumnType("float");

                    b.Property<double?>("MED_TMPTA_SPRR_ALARME_003")
                        .HasPrecision(3, 2)
                        .HasColumnType("float");

                    b.Property<double?>("MED_TMPTA_TRCHO_MDCO_003")
                        .HasPrecision(3, 2)
                        .HasColumnType("float");

                    b.Property<double?>("MED_VOLUME_BRTO_CRRGO_MVMDO_001")
                        .HasPrecision(6, 5)
                        .HasColumnType("float");

                    b.Property<double?>("MED_VOLUME_BRUTO_MVMDO_001")
                        .HasPrecision(6, 5)
                        .HasColumnType("float");

                    b.Property<double?>("MED_VOLUME_LIQUIDO_MVMDO_001")
                        .HasPrecision(6, 5)
                        .HasColumnType("float");

                    b.Property<double?>("MED_VOLUME_TTLZO_FIM_PRDO_001")
                        .HasPrecision(10, 2)
                        .HasColumnType("float");

                    b.Property<double?>("MED_VOLUME_TTLZO_INCO_PRDO_001")
                        .HasPrecision(10, 2)
                        .HasColumnType("float");

                    b.Property<Guid?>("MeasuringEquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NUM_SERIE_1_001")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_1_002")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_1_003")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_2_001")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_2_002")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_2_003")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_3_001")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_3_003")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_4_001")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_4_003")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_5_003")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_6_003")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_COMPUTADOR_VAZAO_001")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_COMPUTADOR_VAZAO_002")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_COMPUTADOR_VAZAO_003")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_ELEMENTO_PRIMARIO_001")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_ELEMENTO_PRIMARIO_002")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("NUM_SERIE_ELEMENTO_PRIMARIO_003")
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<double?>("PCT_ADOTADO_CASO_FALHA_1_001")
                        .HasPrecision(3, 3)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_ADOTADO_CASO_FALHA_2_001")
                        .HasPrecision(3, 3)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_AGUA_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_AGUA_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_ARGONIO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_ARGONIO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_CO2_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_CO2_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_CO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_CO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_DECANO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_DECANO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_ETANO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_ETANO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_H2S_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_H2S_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_HELIO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_HELIO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_HEPTANO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_HEPTANO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_HEXANO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_HEXANO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_HIDROGENIO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_HIDROGENIO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_I_BUTANO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_I_BUTANO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_I_PENTANO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_I_PENTANO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_METANO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_METANO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_NITROGENIO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_NITROGENIO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_NONANO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_NONANO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_N_BUTANO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_N_BUTANO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_N_PENTANO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_N_PENTANO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_OCTANO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_OCTANO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_OXIGENIO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_OXIGENIO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_PROPANO_002")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_CROMATOGRAFIA_PROPANO_003")
                        .HasPrecision(6, 6)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_LIMITE_INFERIOR_1_001")
                        .HasPrecision(3, 3)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_LIMITE_INFERIOR_2_001")
                        .HasPrecision(3, 3)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_LIMITE_SUPERIOR_1_001")
                        .HasPrecision(3, 3)
                        .HasColumnType("float");

                    b.Property<double?>("PCT_LIMITE_SUPERIOR_2_001")
                        .HasPrecision(3, 3)
                        .HasColumnType("float");

                    b.Property<double?>("PRZ_DURACAO_FLUXO_EFETIVO_002")
                        .HasPrecision(4, 4)
                        .HasColumnType("float");

                    b.Property<double?>("PRZ_DURACAO_FLUXO_EFETIVO_003")
                        .HasPrecision(4, 4)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_10_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_10_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_11_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_11_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_12_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_12_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_13_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_13_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_14_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_14_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_15_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_15_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_1_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_1_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_2_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_2_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_3_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_3_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_4_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_4_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_5_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_5_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_6_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_6_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_7_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_7_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_8_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_8_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_9_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_K_FACTOR_9_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_10_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_10_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_11_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_11_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_12_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_12_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_13_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_13_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_14_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_14_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_15_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_15_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_1_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_1_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_2_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_2_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_3_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_3_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_4_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_4_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_5_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_5_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_6_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_6_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_7_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_7_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_8_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_8_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_9_001")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<double?>("QTD_PULSOS_METER_FACTOR_9_002")
                        .HasPrecision(8, 2)
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FileTypeId");

                    b.HasIndex("MeasuringEquipmentId");

                    b.HasIndex("UserId");

                    b.ToTable("Measurements", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.Measurements.Volume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DHA_MEDICAO_039")
                        .HasColumnType("date");

                    b.Property<double?>("DHA_MED_DECLARADO_039")
                        .HasPrecision(8, 6)
                        .HasColumnType("float");

                    b.Property<double?>("DHA_MED_REGISTRADO_039")
                        .HasPrecision(8, 6)
                        .HasColumnType("float");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("MeasurementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementId");

                    b.ToTable("Volumes_039", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.MeasuringEquipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Fluid")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TagEquipment")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar");

                    b.Property<string>("TagMeasuringPoint")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId");

                    b.HasIndex("UserId");

                    b.ToTable("MeasuringEquipments", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.Reservoir", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodReservoir")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Reservoirs", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresIn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("UserHttpAgent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.Well", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArtificialLift")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<double?>("BaseOfPerforated")
                        .HasPrecision(10, 2)
                        .HasColumnType("float");

                    b.Property<string>("CategoryAnp")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("CategoryOperator")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("CategoryReclassificationAnp")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("CodWell")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("CodWellAnp")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("CoordX")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("CoordY")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("DatumHorizontal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Latitude4C")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("LatitudeDD")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Longitude4C")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("LongitudeDD")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<bool?>("StatusOperator")
                        .HasColumnType("bit");

                    b.Property<double?>("TopOfPerforated")
                        .HasPrecision(10, 2)
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("TypeBaseCoordinate")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("WaterDepth")
                        .HasPrecision(10, 2)
                        .HasColumnType("float");

                    b.Property<string>("WellOperatorName")
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("UserId");

                    b.ToTable("Wells", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodZone")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("UserId");

                    b.ToTable("Zones", (string)null);
                });

            modelBuilder.Entity("PRIO.Models.Cluster", b =>
                {
                    b.HasOne("PRIO.Models.User", "User")
                        .WithMany("Clusters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRIO.Models.Completion", b =>
                {
                    b.HasOne("PRIO.Models.Reservoir", "Reservoir")
                        .WithMany("Completions")
                        .HasForeignKey("ReservoirId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PRIO.Models.User", "User")
                        .WithMany("Completions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PRIO.Models.Well", "Well")
                        .WithMany("Completions")
                        .HasForeignKey("WellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservoir");

                    b.Navigation("User");

                    b.Navigation("Well");
                });

            modelBuilder.Entity("PRIO.Models.Field", b =>
                {
                    b.HasOne("PRIO.Models.Installation", "Installation")
                        .WithMany("Fields")
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRIO.Models.User", "User")
                        .WithMany("Fields")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Installation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRIO.Models.Installation", b =>
                {
                    b.HasOne("PRIO.Models.Cluster", "Cluster")
                        .WithMany("Installations")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PRIO.Models.User", "User")
                        .WithMany("Installations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cluster");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRIO.Models.Measurements.Bsw", b =>
                {
                    b.HasOne("PRIO.Models.Measurements.Measurement", "Measurement")
                        .WithMany("LISTA_BSW")
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("PRIO.Models.Measurements.Calibration", b =>
                {
                    b.HasOne("PRIO.Models.Measurements.Measurement", "Measurement")
                        .WithMany("LISTA_CALIBRACAO")
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("PRIO.Models.Measurements.Measurement", b =>
                {
                    b.HasOne("PRIO.Models.FileType", "FileType")
                        .WithMany("Measurements")
                        .HasForeignKey("FileTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRIO.Models.MeasuringEquipment", "MeasuringEquipment")
                        .WithMany("Measurements")
                        .HasForeignKey("MeasuringEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PRIO.Models.User", "User")
                        .WithMany("Measurements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FileType");

                    b.Navigation("MeasuringEquipment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRIO.Models.Measurements.Volume", b =>
                {
                    b.HasOne("PRIO.Models.Measurements.Measurement", "Measurement")
                        .WithMany("LISTA_VOLUME")
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("PRIO.Models.MeasuringEquipment", b =>
                {
                    b.HasOne("PRIO.Models.Installation", "Installation")
                        .WithMany("MeasuringEquipments")
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRIO.Models.User", "User")
                        .WithMany("MeasuringEquipments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Installation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRIO.Models.Reservoir", b =>
                {
                    b.HasOne("PRIO.Models.User", "User")
                        .WithMany("Reservoirs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PRIO.Models.Zone", "Zone")
                        .WithMany("Reservoirs")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("PRIO.Models.Session", b =>
                {
                    b.HasOne("PRIO.Models.User", "User")
                        .WithOne("Session")
                        .HasForeignKey("PRIO.Models.Session", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRIO.Models.Well", b =>
                {
                    b.HasOne("PRIO.Models.Field", "Field")
                        .WithMany("Wells")
                        .HasForeignKey("FieldId");

                    b.HasOne("PRIO.Models.User", "User")
                        .WithMany("Wells")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Field");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRIO.Models.Zone", b =>
                {
                    b.HasOne("PRIO.Models.Field", "Field")
                        .WithMany("Zones")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRIO.Models.User", "User")
                        .WithMany("Zones")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Field");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRIO.Models.Cluster", b =>
                {
                    b.Navigation("Installations");
                });

            modelBuilder.Entity("PRIO.Models.Field", b =>
                {
                    b.Navigation("Wells");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("PRIO.Models.FileType", b =>
                {
                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("PRIO.Models.Installation", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("MeasuringEquipments");
                });

            modelBuilder.Entity("PRIO.Models.Measurements.Measurement", b =>
                {
                    b.Navigation("LISTA_BSW");

                    b.Navigation("LISTA_CALIBRACAO");

                    b.Navigation("LISTA_VOLUME");
                });

            modelBuilder.Entity("PRIO.Models.MeasuringEquipment", b =>
                {
                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("PRIO.Models.Reservoir", b =>
                {
                    b.Navigation("Completions");
                });

            modelBuilder.Entity("PRIO.Models.User", b =>
                {
                    b.Navigation("Clusters");

                    b.Navigation("Completions");

                    b.Navigation("Fields");

                    b.Navigation("Installations");

                    b.Navigation("Measurements");

                    b.Navigation("MeasuringEquipments");

                    b.Navigation("Reservoirs");

                    b.Navigation("Session");

                    b.Navigation("Wells");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("PRIO.Models.Well", b =>
                {
                    b.Navigation("Completions");
                });

            modelBuilder.Entity("PRIO.Models.Zone", b =>
                {
                    b.Navigation("Reservoirs");
                });
#pragma warning restore 612, 618
        }
    }
}
