using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PRIO.src.Modules.Measuring.WellEvents.EF.Models;

namespace PRIO.src.Modules.Measuring.WellEvents.EF.Mappings
{
    public class WellEventMap : IEntityTypeConfiguration<WellEvent>
    {
        public void Configure(EntityTypeBuilder<WellEvent> builder)
        {
            builder.ToTable
                    ("WellEvents");

            builder.Property(x => x.Description)
                .HasColumnType("TEXT");

            builder.Property(x => x.Interval)
                .HasColumnType("float")
                .HasPrecision(15, 6);

            builder.Property(x => x.IdAutoGenerated)
              .HasColumnType("VARCHAR")
              .HasMaxLength(40)
              .IsRequired();

            builder.Property(x => x.EventStatus)
              .HasColumnType("char")
              .HasMaxLength(1);

            builder.Property(x => x.SystemRelated)
              .HasColumnType("varchar")
              .HasMaxLength(20);

            builder.Property(x => x.StatusANP)
              .HasColumnType("VARCHAR")
              .HasMaxLength(100);

            builder.Property(x => x.StateANP)
              .HasColumnType("VARCHAR")
              .HasMaxLength(100);

            builder.HasOne(c => c.Well).
                WithMany(u => u.WellEvents)
                .OnDelete(DeleteBehavior.NoAction)
                .IsRequired();
        }
    }
}
